server:
  port: 5000
  servlet:
    context-path: /pub-sub-messaging

spring:
  application:
    version: 1.0.0
    title: pub-sub-messaging

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:book
    username: admin
    password: 123456
    driverClassName: org.h2.Driver

  h2:
    console.enabled: true
    console.path: /h2-console
    settings.trace: false
    settings.web-allow-others: false

aws:
  region: "${AWS_REGION}"
  sqs:
    base-url: "https://sqs.${aws.region}.amazonaws.com"
    register-book-url: "${aws.sqs.base-url}/${AWS_ACCOUNT}/sqs-register-book"

